### ISSUE TITLE
Retail prices are being rounded down

### ISSUE THREAD

**Issue by barrymcgee** [ynnoj/gatsby-source-printful#22] opened 2020-05-29 13:34 UTC
I contacted Printful Dev Support directly about this and they have indicated the bug is with the middleware - setting a price to be $39.99 in the Printful admin panel results in the price being returned as 3900?

<img width="1440" alt="Screenshot 2020-05-28 at 23 42 27" src="https://user-images.githubusercontent.com/505570/83265386-5a0c5200-a1b9-11ea-800a-8572918f5320.png">

<img width="1352" alt="Screenshot 2020-05-28 at 23 42 14" src="https://user-images.githubusercontent.com/505570/83265375-5678cb00-a1b9-11ea-839e-3ebf39b4b656.png">

**Comment by ynnoj** [comment] 2020-05-29 14:29
Duplicate of #14, which has a pending fix (#17).

**Closed by ynnoj** 2020-05-29 14:29 UTC
Labels: duplicate
